#!/bin/bash

. "$(dirname $0)/config"
. "$(dirname $0)/db-functions"

if [ $# -lt 3 ]; then
	msg "usage: ${0##*/} <repo> <arch> <pkgfile> ..."
	exit 1
fi

repo="$1"
arch="$2"
pkgfiles=(${@:3})

ftppath="$FTP_BASE/$repo/os"

if ! check_repo_permission $repo; then
	die "You don't have permission to add packages to ${repo}"
fi

if [ "$arch" == "all" ]; then
	tarches=(${ARCHES[@]})
else
	tarches=("$arch")
fi

for tarch in ${tarches[@]}; do
	repo_lock $repo $tarch || exit 1
done

msg "Adding packages for [$repo]..."

errored=false
for pkgfile in ${pkgfiles[@]}; do
	if [[ -f "$pkgfile" ]]; then
		if $REQUIRE_SIGNATURE && [[ ! -f "${pkgfile}.sig" ]]; then
			error "Package signature ${pkgfile}.sig not found!"
			errored=true
			break
		fi
		arch_add_to_pool "$pkgfile"
	fi

	for tarch in ${tarches[@]}; do
		msg2 "$tarch\t${pkgfile##*/}"
		arch_db_add $repo $tarch $pkgfile
	done
done

if ! $errored; then
	arch_history_commit "db-add: ${tarches[*]}: ${pkgfiles[*]##*/}"
fi

for tarch in ${tarches[@]}; do
	repo_unlock $repo $tarch
done
