#!/bin/bash

. "$(dirname $0)/config"
. "$(dirname $0)/db-functions"

if [ $# -lt 3 ]; then
	msg "usage: ${0##*/} <repo> <arch> <pkgfile> ..."
	exit 1
fi

repo="$1"
arch="$2"
pkgfiles=(${@:3})

ftppath="$FTP_BASE/$repo/os"

if ! check_repo_permission $repo; then
	die "You don't have permission to add packages to ${repo}"
fi

if [ "$arch" == "all" ]; then
	tarches=(${ARCHES[@]})
else
	tarches=("$arch")
fi

for tarch in ${tarches[@]}; do
	repo_lock $repo $tarch || exit 1
done

for pkgfile in ${pkgfiles[@]}; do
	if [[ -f "$pkgfile" ]]; then
		# TODO: check for signature before adding
		arch_add_to_pool "$pkgfile"
	fi
done

for tarch in "${tarches[@]}"; do
	arch_db_add $repo $tarch "${pkgfiles[@]}"
done

arch_history_commit "db-add: ${tarches[@]}: ${pkgfiles[@]}"

for tarch in ${tarches[@]}; do
	repo_unlock $repo $tarch
done
