#!/bin/bash

. "$(dirname $0)/config"
. "$(dirname $0)/db-functions"

if [ $# -lt 3 ]; then
	msg "usage: ${0##*/} <repo> <arch> <pkgname|pkgbase> ..."
	exit 1
fi

repo="$1"
arch="$2"
pkgbases=(${@:3})

ftppath="$FTP_BASE/$repo/os"

if ! check_repo_permission $repo; then
	die "You don't have permission to remove packages from ${repo}"
fi

if [ "$arch" == "all" ]; then
	tarches=(${ARCHES[@]})
else
	tarches=("$arch")
fi

for tarch in ${tarches[@]}; do
	repo_lock $repo $tarch || exit 1
done

remove_pkgs=()
for pkgbase in ${pkgbases[@]}; do
	msg "Removing $pkgbase from [${repo}-${arch}]..."
	# TODO: detect split packages; do we even want them to be removed automatically?
	remove_pkgs[${#remove_pkgs[*]}]=$pkgbase
done

for tarch in ${tarches[@]}; do
	arch_db_remove "${repo}" "${tarch}" ${remove_pkgs[@]}
done

arch_history_commit "db-remove: ${remove_pkgs[*]}"

for tarch in ${tarches[@]}; do
	repo_unlock $repo $tarch
done

